//
// Copyright (c) 2024 NVI, Inc.
//
// This file is part of the VLBI set_telegraf utility
// (see https://github.com/nvi-inc/set_telegraf).
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.
//

:doctype: book

= DRAFT set_telegraf for FS computers
E. Himwich, C. Frock, C. Coughlin, K. Imai
Version 0.0 - October 2024

:sectnums:

:toc:
== Introduction

The _set_telegraf_ utility can be used to change the state of
_telegraf_ data collection between _full_ and _partial_. In addition
when it is set to _full_, the _gromet_ and _metclient_ services are
enabled; when setting to _partial_, those services are disabled.

Currently, this functionality is only needed for systems with RDBE
back ends that have _operational_ and _spare_ FS computers. Only one
_full_ data collection should occur among the two computers. The other
computer should only use a _partial_ data collection, which is
basically computer health monitoring.

Normally FS operation occurs on the _operational_ computer, which is
typically running the _fs1_ system. If the disks for the _fs1_ system
suffer a catastrophic failure, it will be necessary to move operations
to the _fs2_ system, probably running on the _spare_ computer. The
_set_telegraf_ utility provides a way to switch the configuration as
needed.

The _set_telegraf_ script, assumes `systemd` (not `initd`) is being
used. This script can be used by _root_ (or optionally an AUID
account) to change which system, _fs1_ or _fs2_, runs _telegraf_ (and
_gromet_ and _metclient_) for operations. It can also be used just to
set the configuration on a system with _full_ to _partial_ to disable
use of _gromet_ and _metclient_.

== set_telegraf installation

The actions for installing _set_telegraf_ on _fs1_ and _fs2_ are
almost identical. The two differences are noted as **IMPORTANT** in
the step <<fs1 set_telegraf installation>> below and summarized in
<<fs2 set_telegraf installation>> step below.

The instructions assume that _telegraf_ (and _gromet_ and _metclient_)
have been installed. On the system being used for operations (usually
_fs1_), _telegraf_ should be in the _full_ configuration (described
below) and _gromet_ and _metclient_ services should be enabled. On the
system (usually _fs2_), _telegraf_ should be in the _partial_
configuration (see below) and the _gromet_ and _metclient_ services
should be disabled.

The _full_ configuration for _telegraf_ points the symblic link
_/etc/telegraf/telegraf.conf_ to _/etc/telegraf/telegraf.conf.full_.
For the _partial_ configuration, the link points to
_/etc/telegraf.conf.partial_.

CAUTION: It is strongly recommended that _gromet_ and all its clients,
including _telegraf_ (as set in _/etc/telegraf/telegraf.conf_), use
the _met_server_ (or something other unique) alias as the host name
for _gromet_. This allows the interface to be changed between the
local interface (`127.0.0.1`) and the external interface (the IP
address of the machine) just by editing _/etc/hosts_ and changing
which interface the alias is assigned to and restarting _gromet_ and
all its clients. Further, _fs1_ and _fs2_ should use the same alias
and interface, either the local interface or the external interface
for that system. This allows the (back up) FS on _fs2_ to access the
correct interface if it is used for operations without changing
_/usr2/control/equip.ctl_.

=== fs1 set_telegraf installation

These instructions are performed on _fs1_ by _root_. To install the
_set_telegraf_ script:

IMPORTANT: For installing on _fs2_, these instructions are performed
on _fs2_.

. Clone the _set_telegraf_ repository:

   cd /usr2
   git clone https://github.com/nvi-inc/set_telegraf.git
   chown -R prog.rtx set_telegraf

. Place a copy of _set_telegraf_ in _/usr/local/sbin_ and set
permissions:

  cd /usr/local/sbin
  cp /usr2/set_telegraf/set_telegraf .
  chmod u+rwx,go+r,go-wx set_telegraf

. Enable use with _sudo_ from AUID accounts (optional)

+

If you installed the CIS hardening, you can enable use of
_set_telegraf_ from AUID accounts that are part of the _operators_
group.

.. Place a copy of the script that runs _set_telegraf_ with _sudo_ in
_/usr/local/bin_ and set permissions:

  cd /usr/local/bin
  cp /usr2/set_telegraf/set_telegraf.sudo set_telegraf
  chmod u+rwx,go+rx,go-w set_telegraf

.. Run _visudo_, then add at end:

  %operators	ALL=(ALL) /usr/local/sbin/set_telegraf

==== fs2 set_telegraf installation

The directions for _fs2_ are identical to the ones for _fs1_, except:

* All work is performed on _fs2_

Please follow the directions in the <<fs1 set_telegraf installation>>
sub-section above with those changes, which are noted as **IMPORTANT**
there, then proceed to the step <<Testing set_telegraf>> below.

=== Testing set_telegraf

The instructions below, alternately disable and enable _telegraf_ from
collecting antenna data, and met. data. 

CAUTION: Be careful to enter the command on the machine indicated.

. On _fs1_ as _root_, execute:

  set_telegraf partial

. Verify that the _grafana_ display is _not_ showing updating
antenna/met. data.

. On _fs2_ as _root_, execute:

  set_telegraf full

. Verify that the _grafana_ display is showing updating antenna/met.
data.

. On _fs2_ as _root_, execute:

  set_telegraf partial

. Verify that the _grafana_ display is _not_ showing updating
antenna/met. data.

. On _fs1_ as _root_, execute:

  set_telegraf full

. Verify that the _grafana_ display is showing updating antenna/met.
data.

If in each case _grafana_ was showing or not showing the data as
indicated, then the system is checked out and has been returned to the
_full_ configuration _telegraf_ being on _fs1_. The _partial_
configuration _telegraf_ on _fs2_ should still be collecting
diagnostic information for that system. This is the normal
configuration.

=== Use of set_telegraf

The _set_telegraf_ utility provides a command that can be used to
switch the configuration of _telegraf_ on the _fs1_ and _fs2_ systems.
The _telegraf_ configuration on the _fs1_ system (normally in the
_operational_ chassis) is usually the _full_ configuration, collecting
data from the antenna, FS, datalogger, and met. server, as well as the
performance data for that system. The configuration on the _fs2_
system (normally in the _spare_ chassis) is the _partial_
configuration.  It only collects the performance data for that system.
If for some reason the _fs1_ disk can't be used (in either the
_operational_ or _spare_ computer chassis) and _fs2_ disks are pressed
into service for operations, _set_telegraf_ provides a means to change
the _telegraf_ configuration on the _fs1_ disks to the _partial_ one
and the configuration on the _fs2_ disks into the _full_ one.

NOTE: The node names of the systems are associated with the disks, not
the computer chassis. Thus if the _fs1_ disks are moved from the usual
_operational_ computer chassis to the _spare_ computer chassis, then
_fs1_ is running in the _spare_ computer chassis. If the _fs1_ disks
are moved to the _spare_ chassis, they can still be used for
operations, including using the _full_ configuration of _telegraf_.

IMPORTANT: It is important that only one system use the _full_
configuration of _telegraf_ at any given time. As a result, you should
always change the current _full_ configuration to _partial_ before
enabling the _full_ configuration on the other system. If it is not
possible to disable the current _full_ configuration (for example, the
disks won't boot) before enabling it on the disks, the system with the
previous _full_ configuration should be kept off the network until it
has been switched to _partial_. This can be done either be keeping it
turned off or disconnecting it from the network.

NOTE: If your system is CIS hardened and use of _sudo_ has been able
for _set_telegraf_, all the commands below can be executed from AUID
accounts that are part of the _operators_ group. The AUID user will
typically be prompted to enter their AUID account password.

. When moving operations to the _fs2_ system:

+

To switch the _full_ configuration from _fs1_ to _fs2_:

... Change the _telegraf_ on the _fs1_ disks to `partial`, as _root_
(or using an AUID account):

   set_telegraf partial

... Change the _telegraf_ on the _fs2_ disks to `full`, as _root_ (or
using an AUID account):

   set_telegraf full

... If _gromet_ was serving data to the network instead of
`127.0.0.1`, i.e., the alias for _gromet_ (usually `met_server`) is
assigned to to external interface, you will need to adjust all other
systems that were getting met. data from _fs1_ to point to _fs2_
instead.

. When operations can be restored to the _fs1_ system, switch the
systems back:

+

To switch the _full_ configuration from _fs2_ to _fs1_:

... Change the _telegraf_ on the _fs2_ disks to `partial`, as _root_
(or using an AUID account):

   set_telegraf partial

... Change the _telegraf_ on the _fs1_ disks to `full`, as _root_ (or
using an AUID account):

   set_telegraf full

... If _gromet_ was serving data to the network instead of
`127.0.0.1`, you will need to adjust all other systems that were
getting met. data from _fs2_ to point to _fs1_ instead.
